FROM python:3.12-slim AS builder

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc

COPY requirements.txt .

RUN pip wheel --no-cache-dir --wheel-dir /app/wheels -r requirements.txt

FROM python:3.12-slim

WORKDIR /app

COPY --from=builder /app/wheels /wheels
COPY --from=builder /app/requirements.txt .

RUN pip install --no-cache /wheels/*

COPY services/ /app/services
COPY common/ /app/common
COPY migrations /app/migrations
COPY alembic.ini /app/

EXPOSE 8000
COPY gateway-entrypoint.sh gateway_entrypoint.sh
RUN chmod +x gateway_entrypoint.sh

RUN addgroup --system gatewayUser && adduser --system --group gatewayUser
RUN chown -R gatewayUser:gatewayUser /app
USER gatewayUser


ENTRYPOINT ["./gateway_entrypoint.sh"]
CMD [ "uvicorn", "services.gateway.main:app", "--port", "8000", "--host", "0.0.0.0"]