FROM python:3.12-slim AS builder

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc

COPY requirements.txt .

RUN pip wheel --no-cache-dir --wheel-dir /app/wheels -r requirements.txt

FROM python:3.12-slim

WORKDIR /app

COPY --from=builder /app/wheels /wheels
COPY --from=builder /app/requirements.txt .

RUN pip install --no-cache /wheels/*

COPY services/gateway /app/services/gateway
COPY common/ /app/common

RUN addgroup --system gatewayUser && adduser --system --group gatewayUser
USER gatewayUser

ENTRYPOINT [ "python3", "-u", "-m",  "services.gateway.settlement_consumer" ]