"""Refactor status to native postgres enums

Revision ID: a0d1dd8213b4
Revises: 74357533c98b
Create Date: 2026-03-18 20:51:49.504696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a0d1dd8213b4'
down_revision: Union[str, Sequence[str], None] = '74357533c98b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    ## Explicetly Create Enum data types
    op.execute("CREATE TYPE outboxstatus AS ENUM ('PENDING', 'PROCESSED');")
    op.execute(
        "CREATE TYPE transactionstatus AS ENUM ('PENDING', 'COMPLETED', 'APPROVED', 'REJECTED', 'BLOCKED');")
    
    op.alter_column('outbox', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=postgresql.ENUM('PENDING', 'PROCESSED', name='outboxstatus'),
               existing_nullable=False,
               postgresql_using='status::text::outboxstatus')
    op.alter_column('transactions', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=postgresql.ENUM('PENDING', 'COMPLETED', 'APPROVED', 'REJECTED', 'BLOCKED', name='transactionstatus'),
               existing_nullable=False,
               postgresql_using='status::text::transactionstatus')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'status',
               existing_type=postgresql.ENUM('PENDING', 'COMPLETED', 'APPROVED', 'REJECTED', 'BLOCKED', name='transactionstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('outbox', 'status',
               existing_type=postgresql.ENUM('PENDING', 'PROCESSED', name='outboxstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.execute("DROP TYPE transactionstatus;")
    op.execute("DROP TYPE outboxstatus;")
    # ### end Alembic commands ###
