"""Add auth and account mapping tables

Revision ID: c09325337925
Revises: f8426436713f
Create Date: 2026-04-28 22:44:57.983193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c09325337925'
down_revision: Union[str, Sequence[str], None] = 'f8426436713f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('account_type', postgresql.ENUM('CHECKING', 'SAVINGS', name='accounttype'), nullable=False),
    sa.Column('account_status', postgresql.ENUM('ACTIVE', 'FROZEN', 'CLOSED', name='accountstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('kyc_status', postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', name='kycstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('account_mappings',
    sa.Column('mapping_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('role', postgresql.ENUM('OWNER', 'JOINT_OWNER', 'AUTHORIZED_USER', 'POA', 'POD', 'ADMINISTRATOR', name='accountaccessrole'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('mapping_id')
    )
    op.create_index(op.f('ix_account_mappings_account_id'), 'account_mappings', ['account_id'], unique=False)
    op.create_index(op.f('ix_account_mappings_user_id'), 'account_mappings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_mappings_user_id'), table_name='account_mappings')
    op.drop_index(op.f('ix_account_mappings_account_id'), table_name='account_mappings')
    op.drop_table('account_mappings')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('accounts')
    # ### end Alembic commands ###
