"""add outbox and timezone awareness

Revision ID: 281d90de8c60
Revises: 736148e9c2a3
Create Date: 2026-04-15 22:41:39.701479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '281d90de8c60'
down_revision: Union[str, Sequence[str], None] = '736148e9c2a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'PROCESSED', name='outboxstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_outbox_topic'), 'outbox', ['topic'], unique=False)
    op.alter_column('ledger_transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ledger_transactions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_outbox_topic'), table_name='outbox')
    op.drop_table('outbox')
    # ### end Alembic commands ###
