"""add_master_account_exemption

Revision ID: 406f83bb92a1
Revises: 83b3384050bb
Create Date: 2026-04-03 00:24:45.880227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '406f83bb92a1'
down_revision: Union[str, Sequence[str], None] = '83b3384050bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop old constraint if exist
    op.execute(
        "ALTER TABLE accounts DROP CONSTRAINT IF EXISTS chk_accounts_balance_positive;"
    )
    
    # Add new constraint
    op.execute("""
        ALTER TABLE accounts
        ADD CONSTRAINT chk_accounts_balance_positive_or_master
        CHECK (balance_cents >= 0 OR account_id = '00000000-0000-0000-0000-000000000000'::uuid);
    """)
    
    # Add the master bank account
    op.execute("""
        INSERT INTO accounts (account_id, balance_cents)
        VALUES ('00000000-0000-0000-0000-000000000000'::uuid, 0)
        ON CONFLICT (account_id) DO NOTHING;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Delete new constraint
    op.execute(
        "ALTER TABLE accounts DROP CONSTRAINT IF EXISTS chk_accounts_balance_positive_or_master;")

    # 2. Restore the strict constraint
    op.execute("""
        ALTER TABLE accounts 
        ADD CONSTRAINT chk_accounts_balance_positive 
        CHECK (balance_cents >= 0);
    """)
    # ### end Alembic commands ###
