"""Alter table LedgerTransaction to add stasus and remove is_posted flag

Revision ID: 736148e9c2a3
Revises: 406f83bb92a1
Create Date: 2026-04-15 00:00:34.713537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '736148e9c2a3'
down_revision: Union[str, Sequence[str], None] = '406f83bb92a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "CREATE TYPE transactionstatus AS ENUM ('PENDING', 'COMPLETED', 'APPROVED', 'REJECTED', 'BLOCKED');")
    op.add_column('ledger_transactions', sa.Column('status', postgresql.ENUM('PENDING', 'COMPLETED', 'APPROVED', 'REJECTED', 'BLOCKED', name='transactionstatus'), nullable=False))
    op.drop_column('ledger_transactions', 'is_posted')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ledger_transactions', sa.Column('is_posted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('ledger_transactions', 'status')
    op.execute("DROP TYPE transactionstatus;")
    # ### end Alembic commands ###
