FROM python:3.12-slim AS builder

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc

COPY requirements.txt .

RUN pip wheel --no-cache-dir --wheel-dir /app/wheels -r requirements.txt

FROM python:3.12-slim

WORKDIR /app

COPY --from=builder /app/wheels /wheels
COPY --from=builder /app/requirements.txt .

RUN pip install --no-cache /wheels/*

COPY services/ledger /app/services/ledger
COPY common/ /app/common

COPY services/ledger/entrypoint.sh entrypoint.sh
RUN chmod +x entrypoint.sh

RUN addgroup --system ledgerUser && adduser --system --group ledgerUser
RUN chown -R ledgerUser:ledgerUser /app
USER ledgerUser


ENTRYPOINT ["./entrypoint.sh"]
CMD [ "python3", "-u", "-m", "services.ledger.main"]